name: Cypress-Cucumber Tests
on:
    push:
        branches: [master, main]
jobs:
    Run_test:
        runs-on: ubuntu-20.04 # Choosing OS
        strategy:
            matrix:
                node-version: [14.17.0]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - name: update node manager
              run: npm i npm@latest
            - name: install all dependencies
              run: npm i
            - name: run test
              run: npx cypress run --config-file config/config.js
            - name: Upload artifact cucumber-report
              uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: cucumber-report
                  path: ./cucumber-report.html
                  retention-days: 5 
            - name: put report to docs
              if: always()
              run: cp -R cucumber-report.html ./docs/reports/
